### ISSUE TITLE
Using dot as thousandSeparator

### ISSUE THREAD

**Issue by jeff1985** [johnjcamilleri/jquery-spincrement#1]
You did not specify, the exact type for the parameters of your plugin. So i assume decimalPoint and thousandSeparator are supposed to be just string. 

So i tried to specify german number format as follows:     

```
var options = {
      decimalPoint: ",",
      thousandSeparator: "."
};
```

This however results in all spincremented numbers beeing displayed as "NaN". 

The actual problem is that in the code you create a regular expression out of this parameter:

```
var re = new RegExp(options.thousandSeparator, 'g')
to = parseFloat(obj.text().replace(re, '')) 
```

Dot is a special character in RegExp and it matches any char. 

It is however also not possible to specify a regular expression as thousandSeparator, because it will then also be used for formatting and will be printed as part of the number. 

So my guess, is that escaping is missing somewhere in your code...

**Comment by johnjcamilleri** [comment]
You're probably right — this plugin is very old and I haven't used it in years. But I'd be glad if you submitted a pull request fixing the issue :)

**Comment by srnden** [comment]
Change
`var re = new RegExp(options.thousandSeparator, 'g')`
to
`var ts = $.inArray(options.thousandSeparator, ["\\", "^", "$", "*", "+", "?", "."]) > -1 ? '\\'+options.thousandSeparator : options.thousandSeparator;`
`var re = new RegExp(ts, 'g')`
It must help:)

**Comment by johnjcamilleri** [comment]
Thanks for the code @spacerangerniko. This has now been updated in commit 7f404fb.
